### ISSUE TITLE
Requesting for adding a new paper

### ISSUE THREAD

**Issue by ChandlerBang** [nancheng58/Awesome-LLM4RS-Papers#15]
Dear Repo Owner,

Thank you for maintaining this nice repo of LLM for Recommendation. We have recently released a session-recommendation dataset named [Amazon-M2](https://arxiv.org/abs/2307.09688) for evaluating LLMs in recommendation scenarios. It provides both a dataset, a benchmark, and three text-related tasks. Would you mind adding this work to your repo?

Thank you for your attention.

**Comment by nancheng58** [comment]
Dear Professor Wei Jin, 

Thanks for your interest! I added your excellent work in this repo.
