### ISSUE TITLE
Request for adding new paper and datasets

### ISSUE THREAD

**Issue by AaronHeee** [nancheng58/Awesome-LLM4RS-Papers#19]
Hi @nancheng58,

Thanks so much for sharing such a nice repo on LLMs for Rec! I am wondering if our recent paper [Large Language Models as Zero-Shot Conversational Recommenders](https://github.com/AaronHeee/LLMs-as-Zero-Shot-Conversational-RecSys) could be included in this list?

Our contributions include (1) **datasets**: new conversational recommendation datasets from Reddit; (2) **LLMs** evaluation on conversational recommendation tasks and related analysis.

Thanks in advance!

**Comment by nancheng58** [comment]
Thanks for your excellent work! I will add it to this repo.
