### ISSUE TITLE
Adding a new LLM RecSys paper LlamaRec: Two-Stage Recommendation using Large Language Models for Ranking

### ISSUE THREAD

**Issue by Yueeeeeeee** [nancheng58/Awesome-LLM4RS-Papers#21]
Hi @nancheng58,

Thank you for maintaining this repo of LLM Recsys, we recently release a workshop paper call LlamaRec for LLM-based sequential recommender. The paper can be found at https://github.com/Yueeeeeeee/LlamaRec/blob/main/media/paper.pdf (ArXiv will be available soon) and the code can be found at: https://github.com/Yueeeeeeee/LlamaRec

Would you mind adding this work to your repo as well? Thank you!

**Comment by nancheng58** [comment]
Hi @Yueeeeeeee,
Thanks for your nice work about LLM4SR, I added it to this repo.
