### ISSUE TITLE
Add "Language models as recommender systems: Evaluations and limitations"

### ISSUE THREAD

**Issue by yuhui-zh15** [nancheng58/Awesome-LLM4RS-Papers#22]
Hi @nancheng58,

Thank you for maintaining this great repo! We had a paper published in 2021 titled "[Language models as recommender systems: Evaluations and limitations](https://www.amazon.science/publications/language-models-as-recommender-systems-evaluations-and-limitations)". This is the first work leveraging pre-trained LLMs for recommendation using prompting methods. Would you like to add this work to your repo?

**Comment by nancheng58** [comment]
Thanks for your nice work, I added it to this repo.
