### ISSUE TITLE
Request of adding new works 

### ISSUE THREAD

**Issue by youhua97** [nancheng58/Awesome-LLM4RS-Papers#28]
Hi, we recently came across your project and were impressed by its scope and objectives. We believe that our research papers could be a valuable addition to your project as references:

 1 NineRec: A Benchmark Dataset Suite for Evaluating Transferable Recommendation
        Link: https://arxiv.org/pdf/2309.07705.pdf
  2 A Content-Driven Micro-Video Recommendation Dataset at Scale
        Link: https://arxiv.org/pdf/2309.15379.pdf

We kindly request you to consider including our papers in your project. If you require any additional information or have any questions, please do not hesitate to contact us.

**Comment by nancheng58** [comment]
Hi,
Thanks for your interesting work! I added them to this repo.
