### ISSUE TITLE
Kindly request of adding one new paper

### ISSUE THREAD

**Issue by JinghaoZ** [nancheng58/Awesome-LLM4RS-Papers#29]
Hi! Thank you for creating and maintaining such a great repository! There is a new paper that reveals the security vulnerabilities of LLM-based RS due to their emphasis on the textual content of items:

Stealthy Attack on Large Language Model based Recommendation
Link: https://arxiv.org/abs/2402.14836

We kindly request you to consider including our paper in your repository. Thank you very much!

**Comment by nancheng58** [comment]
Thanks for your nice work! I will add it to this repo.
