### ISSUE TITLE
Created a PR to add a survey paper based on LLMs in recommender System

### ISSUE THREAD

**Issue by arpita8** [nancheng58/Awesome-LLM4RS-Papers#51]
Hi,
I have created this new [PR](https://github.com/nancheng58/Awesome-LLM4RS-Papers/pull/50), for adding one of the most recent survey paper on LLMs in Recommender System, The paper added in this PR was arxived in 2024, so it has all the recent work done in this area so far. I will like this paper to be added in your github  list under survey paper. Thanks

**Comment by nancheng58** [comment]
Thanks for your contribution and I have already merged it.
