### ISSUE TITLE
Could you update one LLM-based Recommendation paper?

### ISSUE THREAD

**Issue by ghdtjr** [nancheng58/Awesome-LLM4RS-Papers#52]
Dear Authors,

Thank you for your valuable contributions to the recommender system community! I wanted to ask if you could kindly add another paper to your GitHub repository. The paper, "A-LLMRec: Large Language Models meet Collaborative Filtering: An Efficient All-round LLM-based Recommender System", has been accepted at KDD 2024. It explores leveraging collaborative knowledge from a pre-trained collaborative filtering recommender system to LLMs. You can find the paper at this link: https://arxiv.org/abs/2404.11343.

Thank you in advance!

**Comment by nancheng58** [comment]
Thanks for your nice work! I added it to this repo.
